# Generated by Django 5.2.3 on 2025-06-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="language",
            field=models.CharField(
                choices=[("Eng", "English"), ("Tur", "Turkish")],
                default="Eng",
                max_length=10,
                verbose_name="Выбор языка",
            ),
        ),
    ]
