# Generated by Django 5.2.3 on 2025-06-20 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmploymentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("surname", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Например: +996707123456",
                        max_length=20,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        upload_to="media/employees/cvs/", verbose_name="Резюме (CV)"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Сообщение или сопроводительное письмо",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на трудоустройство",
                "verbose_name_plural": "Заявки на трудоустройство",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("message", models.TextField(verbose_name="Сообщение")),
            ],
            options={
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "Обратная связь",
            },
        ),
        migrations.CreateModel(
            name="BuyProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("surname", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Например: +996707123456",
                        max_length=20,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_to_buy",
                        to="products.product",
                        verbose_name="Продукт для покупки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на покупку продукта",
                "verbose_name_plural": "Заявки на покупку продукта",
            },
        ),
    ]
